server:
  port: ${PORT:8080}
  
zuul:
  ignoredServices: '*'
  routes:
    greeting:
      path: /greeting/**
      url: http://localhost:2222
      stripPrefix : false

    hello:
      path: /hello/**
      url: http://localhost:3333
      stripPrefix : false
